spring.application.name=domainprobe
domainprobe.rdap.bootstrap-url=${RDAP_BOOTSTRAP_URL:https://data.iana.org/rdap/dns.json}
domainprobe.rdap.timeout=${RDAP_TIMEOUT:5s}
dns.api.base-url=${DNS_BASE_URL:https://dns.google/resolve}
ssl.api.timeout=${SSL_TIMEOUT:5s}
ipinfo.base-url=https://api.ipinfo.io
ipinfo.token=${IPINFO_TOKEN}
gemini.api.key=${GEMINI_API_KEY}
groq.api.key=${GROQ_API_KEY}
groq.base-url=https://api.groq.com/openai/v1
server.port=${PORT:8080}